--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2025-05-29 22:02:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 107957)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 5887 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 238 (class 1259 OID 116681)
-- Name: AnswerImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AnswerImages" (
    "Id" uuid NOT NULL,
    "Uri" text NOT NULL,
    "AnswerId" uuid NOT NULL
);


ALTER TABLE public."AnswerImages" OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 116149)
-- Name: Answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Answers" (
    "Id" uuid NOT NULL,
    "IssueId" uuid NOT NULL,
    "ModeratorId" uuid NOT NULL,
    "Text" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "NewStatus" integer DEFAULT 0 NOT NULL,
    "OldStatus" integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."Answers" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 109060)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 109059)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 109038)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 109073)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 109072)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 109085)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 109097)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 109112)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 109045)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AspNetUsers" (
    "Id" uuid NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    "FullName" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 109052)
-- Name: Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Categories" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text DEFAULT ''::text NOT NULL,
    "ImageUri" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Categories" OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 116654)
-- Name: Comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Comments" (
    "Id" uuid NOT NULL,
    "Text" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid NOT NULL,
    "IssueId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL
);


ALTER TABLE public."Comments" OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 116696)
-- Name: Grades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Grades" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "IssueId" uuid NOT NULL,
    "Like" boolean NOT NULL
);


ALTER TABLE public."Grades" OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 116200)
-- Name: IssueImages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IssueImages" (
    "Id" uuid NOT NULL,
    "Uri" text NOT NULL,
    "IssueId" uuid NOT NULL
);


ALTER TABLE public."IssueImages" OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 109124)
-- Name: Issues; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Issues" (
    "Id" uuid NOT NULL,
    "Title" text NOT NULL,
    "Description" text,
    "Status" character varying(30) NOT NULL,
    "Location" text DEFAULT ''::text NOT NULL,
    "Point" public.geometry,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "CategoryId" uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid NOT NULL,
    "ModifiedById" uuid,
    "ModifiedOn" timestamp with time zone,
    "RevokedById" uuid,
    "RevokedOn" timestamp with time zone
);


ALTER TABLE public."Issues" OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 109141)
-- Name: ModeratorCategories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ModeratorCategories" (
    "ModeratorId" uuid NOT NULL,
    "CategoryId" uuid NOT NULL
);


ALTER TABLE public."ModeratorCategories" OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 116185)
-- Name: RefreshTokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."RefreshTokens" (
    "Id" uuid NOT NULL,
    "Token" text NOT NULL,
    "UserId" uuid NOT NULL,
    "Expires" timestamp with time zone NOT NULL
);


ALTER TABLE public."RefreshTokens" OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 109033)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 5864 (class 0 OID 109038)
-- Dependencies: 222
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
01957d08-0ab4-7282-959f-b9581cbd742c	Admin	ADMIN	\N
01957d08-0b49-76d4-8c31-e32b4ec63173	Moderator	MODERATOR	\N
01957d08-0b5c-7811-9905-27c4ac82cee9	User	USER	\N
\.

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250309222427_InitialCreate	9.0.2
20250316203429_AddAnswers	9.0.2
20250316203608_DelAnswerIdInIssue	9.0.2
20250316215919_AddFullName	9.0.2
20250328174208_UserAndCategoryInIssueIsNullTestTime	9.0.2
20250328223938_AddCategoryDescription	9.0.2
20250330231304_AddRefreshTokens	9.0.2
20250416234535_RenamingAndAddImages	9.0.2
20250417004007_RenameFromNameToTitleForCategories	9.0.2
20250420201241_RemoveNullsInIssue	9.0.2
20250420205922_NullIssueDescription	9.0.2
20250502195529_AddCommentsToIssue	9.0.2
20250502200402_AddIssueToComment	9.0.2
20250502223703_AddStatusAndImagesToAnswer	9.0.2
20250504220750_AddGrades	9.0.2
20250512210955_FullNameIsUnique	9.0.2
20250514203624_CategoryTitleIsUnique	9.0.2
20250516183940_AddModifiedRevoked	9.0.2
\.


--
-- TOC entry 5622 (class 0 OID 108275)
-- Dependencies: 217
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- TOC entry 5888 (class 0 OID 0)
-- Dependencies: 225
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- TOC entry 5889 (class 0 OID 0)
-- Dependencies: 227
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- TOC entry 5689 (class 2606 OID 116695)
-- Name: AnswerImages PK_AnswerImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AnswerImages"
    ADD CONSTRAINT "PK_AnswerImages" PRIMARY KEY ("Id");


--
-- TOC entry 5676 (class 2606 OID 116155)
-- Name: Answers PK_Answers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "PK_Answers" PRIMARY KEY ("Id");


--
-- TOC entry 5651 (class 2606 OID 109066)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 5638 (class 2606 OID 109044)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 5654 (class 2606 OID 109079)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 5657 (class 2606 OID 109091)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 5660 (class 2606 OID 109101)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 5662 (class 2606 OID 109118)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 5644 (class 2606 OID 109051)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 5648 (class 2606 OID 109058)
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- TOC entry 5686 (class 2606 OID 116660)
-- Name: Comments PK_Comments; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "PK_Comments" PRIMARY KEY ("Id");


--
-- TOC entry 5693 (class 2606 OID 116700)
-- Name: Grades PK_Grades; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Grades"
    ADD CONSTRAINT "PK_Grades" PRIMARY KEY ("Id");


--
-- TOC entry 5682 (class 2606 OID 116206)
-- Name: IssueImages PK_IssueImages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IssueImages"
    ADD CONSTRAINT "PK_IssueImages" PRIMARY KEY ("Id");


--
-- TOC entry 5669 (class 2606 OID 109130)
-- Name: Issues PK_Issues; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Issues"
    ADD CONSTRAINT "PK_Issues" PRIMARY KEY ("Id");


--
-- TOC entry 5672 (class 2606 OID 109145)
-- Name: ModeratorCategories PK_ModeratorCategories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ModeratorCategories"
    ADD CONSTRAINT "PK_ModeratorCategories" PRIMARY KEY ("ModeratorId", "CategoryId");


--
-- TOC entry 5679 (class 2606 OID 116191)
-- Name: RefreshTokens PK_RefreshTokens; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id");


--
-- TOC entry 5636 (class 2606 OID 109037)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 5640 (class 1259 OID 109176)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 5687 (class 1259 OID 116693)
-- Name: IX_AnswerImages_AnswerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AnswerImages_AnswerId" ON public."AnswerImages" USING btree ("AnswerId");


--
-- TOC entry 5673 (class 1259 OID 116167)
-- Name: IX_Answers_IssueId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Answers_IssueId" ON public."Answers" USING btree ("IssueId");


--
-- TOC entry 5674 (class 1259 OID 116168)
-- Name: IX_Answers_ModeratorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Answers_ModeratorId" ON public."Answers" USING btree ("ModeratorId");


--
-- TOC entry 5649 (class 1259 OID 109171)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 5652 (class 1259 OID 109173)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 5655 (class 1259 OID 109174)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 5658 (class 1259 OID 109175)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 5641 (class 1259 OID 109177)
-- Name: IX_AspNetUsers_Email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_AspNetUsers_Email" ON public."AspNetUsers" USING btree ("Email");


--
-- TOC entry 5642 (class 1259 OID 116732)
-- Name: IX_AspNetUsers_FullName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_AspNetUsers_FullName" ON public."AspNetUsers" USING btree ("FullName");


--
-- TOC entry 5646 (class 1259 OID 116733)
-- Name: IX_Categories_Title; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Categories_Title" ON public."Categories" USING btree ("Title");


--
-- TOC entry 5683 (class 1259 OID 116671)
-- Name: IX_Comments_IssueId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Comments_IssueId" ON public."Comments" USING btree ("IssueId");


--
-- TOC entry 5684 (class 1259 OID 116672)
-- Name: IX_Comments_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Comments_UserId" ON public."Comments" USING btree ("UserId");


--
-- TOC entry 5690 (class 1259 OID 116711)
-- Name: IX_Grades_IssueId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Grades_IssueId" ON public."Grades" USING btree ("IssueId");


--
-- TOC entry 5691 (class 1259 OID 116712)
-- Name: IX_Grades_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Grades_UserId" ON public."Grades" USING btree ("UserId");


--
-- TOC entry 5680 (class 1259 OID 116212)
-- Name: IX_IssueImages_IssueId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_IssueImages_IssueId" ON public."IssueImages" USING btree ("IssueId");


--
-- TOC entry 5663 (class 1259 OID 109179)
-- Name: IX_Issues_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Issues_CategoryId" ON public."Issues" USING btree ("CategoryId");


--
-- TOC entry 5664 (class 1259 OID 116734)
-- Name: IX_Issues_ModifiedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Issues_ModifiedById" ON public."Issues" USING btree ("ModifiedById");


--
-- TOC entry 5665 (class 1259 OID 116735)
-- Name: IX_Issues_RevokedById; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Issues_RevokedById" ON public."Issues" USING btree ("RevokedById");


--
-- TOC entry 5666 (class 1259 OID 109180)
-- Name: IX_Issues_Status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Issues_Status" ON public."Issues" USING btree ("Status");


--
-- TOC entry 5667 (class 1259 OID 109181)
-- Name: IX_Issues_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Issues_UserId" ON public."Issues" USING btree ("UserId");


--
-- TOC entry 5670 (class 1259 OID 109182)
-- Name: IX_ModeratorCategories_CategoryId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ModeratorCategories_CategoryId" ON public."ModeratorCategories" USING btree ("CategoryId");


--
-- TOC entry 5677 (class 1259 OID 116197)
-- Name: IX_RefreshTokens_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_RefreshTokens_UserId" ON public."RefreshTokens" USING btree ("UserId");


--
-- TOC entry 5639 (class 1259 OID 109172)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 5645 (class 1259 OID 109178)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 5712 (class 2606 OID 116713)
-- Name: AnswerImages FK_AnswerImages_Answers_AnswerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AnswerImages"
    ADD CONSTRAINT "FK_AnswerImages_Answers_AnswerId" FOREIGN KEY ("AnswerId") REFERENCES public."Answers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5706 (class 2606 OID 116156)
-- Name: Answers FK_Answers_AspNetUsers_ModeratorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_AspNetUsers_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5707 (class 2606 OID 116161)
-- Name: Answers FK_Answers_Issues_IssueId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES public."Issues"("Id") ON DELETE CASCADE;


--
-- TOC entry 5694 (class 2606 OID 109067)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5695 (class 2606 OID 109080)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5696 (class 2606 OID 109092)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5697 (class 2606 OID 109102)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 5698 (class 2606 OID 109107)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5699 (class 2606 OID 109119)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5710 (class 2606 OID 116661)
-- Name: Comments FK_Comments_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5711 (class 2606 OID 116674)
-- Name: Comments FK_Comments_Issues_IssueId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Comments"
    ADD CONSTRAINT "FK_Comments_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES public."Issues"("Id") ON DELETE CASCADE;


--
-- TOC entry 5713 (class 2606 OID 116701)
-- Name: Grades FK_Grades_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Grades"
    ADD CONSTRAINT "FK_Grades_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5714 (class 2606 OID 116706)
-- Name: Grades FK_Grades_Issues_IssueId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Grades"
    ADD CONSTRAINT "FK_Grades_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES public."Issues"("Id") ON DELETE CASCADE;


--
-- TOC entry 5709 (class 2606 OID 116207)
-- Name: IssueImages FK_IssueImages_Issues_IssueId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IssueImages"
    ADD CONSTRAINT "FK_IssueImages_Issues_IssueId" FOREIGN KEY ("IssueId") REFERENCES public."Issues"("Id") ON DELETE CASCADE;


--
-- TOC entry 5700 (class 2606 OID 116736)
-- Name: Issues FK_Issues_AspNetUsers_ModifiedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Issues"
    ADD CONSTRAINT "FK_Issues_AspNetUsers_ModifiedById" FOREIGN KEY ("ModifiedById") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 5701 (class 2606 OID 116741)
-- Name: Issues FK_Issues_AspNetUsers_RevokedById; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Issues"
    ADD CONSTRAINT "FK_Issues_AspNetUsers_RevokedById" FOREIGN KEY ("RevokedById") REFERENCES public."AspNetUsers"("Id") ON DELETE SET NULL;


--
-- TOC entry 5702 (class 2606 OID 116240)
-- Name: Issues FK_Issues_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Issues"
    ADD CONSTRAINT "FK_Issues_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5703 (class 2606 OID 116245)
-- Name: Issues FK_Issues_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Issues"
    ADD CONSTRAINT "FK_Issues_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE RESTRICT;


--
-- TOC entry 5704 (class 2606 OID 109146)
-- Name: ModeratorCategories FK_ModeratorCategories_AspNetUsers_ModeratorId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ModeratorCategories"
    ADD CONSTRAINT "FK_ModeratorCategories_AspNetUsers_ModeratorId" FOREIGN KEY ("ModeratorId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 5705 (class 2606 OID 109151)
-- Name: ModeratorCategories FK_ModeratorCategories_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ModeratorCategories"
    ADD CONSTRAINT "FK_ModeratorCategories_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE CASCADE;


--
-- TOC entry 5708 (class 2606 OID 116192)
-- Name: RefreshTokens FK_RefreshTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."RefreshTokens"
    ADD CONSTRAINT "FK_RefreshTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


-- Completed on 2025-05-29 22:02:06

--
-- PostgreSQL database dump complete
--

